package renderer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/VictorM0nteiro/leanBuildDocker/internal/types"
)

// Render writes the Dockerfile and .lbd-report.md to outputDir.
// Phase 3: string-builder output. Phase 4 will replace this with text/template.
func Render(plan *types.BuildPlan, outputDir string) error {
	if err := writeFile(outputDir, "Dockerfile", buildDockerfile(plan)); err != nil {
		return err
	}
	if err := writeFile(outputDir, ".lbd-report.md", buildReport(plan)); err != nil {
		return err
	}
	return nil
}

func buildDockerfile(plan *types.BuildPlan) string {
	var b strings.Builder

	b.WriteString("# Generated by leanBuildDocker (lbd)\n\n")

	b.WriteString("FROM " + plan.BuildStage.BaseImage + " AS builder\n")
	b.WriteString("WORKDIR /src\n")
	b.WriteString("COPY go.mod go.sum ./\n")
	b.WriteString("RUN go mod download\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN " + execForm(plan.BuildStage.BuildCommand) + "\n\n")

	b.WriteString("FROM " + plan.RuntimeStage.BaseImage + "\n")
	if plan.RuntimeStage.WorkingDir != "" {
		b.WriteString("WORKDIR " + plan.RuntimeStage.WorkingDir + "\n")
	}
	b.WriteString(fmt.Sprintf("COPY --from=builder /out/%s %s\n", plan.BinaryName, plan.BinaryPath))
	if plan.RuntimeStage.User != "" {
		b.WriteString("USER " + plan.RuntimeStage.User + "\n")
	}
	for _, p := range plan.RuntimeStage.ExposedPorts {
		b.WriteString(fmt.Sprintf("EXPOSE %d\n", p))
	}
	b.WriteString("ENTRYPOINT " + execForm(plan.RuntimeStage.EntryCommand) + "\n")

	return b.String()
}

func buildReport(plan *types.BuildPlan) string {
	var b strings.Builder
	b.WriteString("# leanBuildDocker Report\n\n")
	b.WriteString("## Decisions\n\n")
	for _, d := range plan.Decisions {
		b.WriteString(fmt.Sprintf("### %s — %s\n\n", d.Topic, d.Chose))
		b.WriteString(d.Because + "\n\n")
		if len(d.Alternatives) > 0 {
			b.WriteString("Alternatives considered:\n")
			for _, a := range d.Alternatives {
				b.WriteString("- " + a + "\n")
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func execForm(args []string) string {
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = fmt.Sprintf("%q", a)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func writeFile(dir, name, content string) error {
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
